/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.telegram:telegrambots:6.0.1")
    api("org.telegram:telegrambotsextensions:6.0.1")
    api("log4j:log4j:1.2.17")
    api("org.slf4j:slf4j-api:1.7.36")
    api("org.slf4j:slf4j-log4j12:1.7.36")
    api("com.fasterxml.jackson.core:jackson-core:2.13.2")
    api("org.jsoup:jsoup:1.14.3")
    testImplementation("junit:junit:4.13.2")
    compileOnly("org.projectlombok:lombok:1.18.24")
}

group = "org.example.botfarm"
version = "1.0-SNAPSHOT"
description = "firsttlgbot"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
